server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    path-match:
      matching-strategy:
        ant_path_matcher
  datasource:
    driver-class-name:
      com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/MZTI
    # url: jdbc:mysql://3.35.231.108:3306/MZTI
    username: root
    password: rlaxogjs8312
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true
  sql.init.mode: always
jwt:
  secret: RlaXoVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

